resource "sase_security_rules" "this" {
  for_each           = try(var.security_rules, {})
  action             = try(each.value.action, "deny")
  name               = try(each.value.name, [])
  source             = try(each.value.source, [])
  destination        = try(each.value.destination, [])
  service            = try(sase_objects_services.this[each.value.service], []) # Evaluate Loop for supporting both individual service, list of services, and service groups
  application        = try(each.value.application, [])
  category           = try(each.value.category, [])
  position           = try(each.value.position, [])
  source_user        = try(each.value.source_user, [])
  to                 = try(each.value.to, [])
  description        = try(each.value.description, null)
  destination_hip    = try(each.value.destionation_hip, null)
  source_hip         = try(each.value.source_hip, null)
  disabled           = try(each.value.disabled, null)
  log_setting        = try(each.value.log_setting, null)
  negate_source      = try(each.value.negate_source, false)
  negate_destination = try(each.value.negate_destination, false)
  profile_setting    = try(each.value.profile_setting, null)
  tag                = try(each.value.tags, null)
}

resource "sase_decryption_rules" "this" {
  for_each           = try(var.decryption_rules, {})
  name               = try(each.value.name, [])
  source             = try(each.value.source, [])
  destination        = try(each.value.destination, [])
  service            = try(each.value.service, [])
  application        = try(each.value.application, [])
  category           = try(each.value.category, [])
  position           = try(each.value.position, [])
  source_user        = try(each.value.source_user, [])
  to                 = try(each.value.to, [])
  description        = try(each.value.description, null)
  destination_hip    = try(each.value.destionation_hip, null)
  disabled           = try(each.value.disabled, null)
  log_setting        = try(each.value.log_setting, null)
  negate_source      = try(each.value.negate_source, false)
  negate_destination = try(each.value.negate_destination, false)
  profile_setting    = try(each.value.profile_setting, null)
  tag                = try(each.value.tags, null)
  type               = try(each.value.type, null)
  profile            = try(each.value.profile, null)
  source_hip         = try(each.value.source_hip, null)
  log_fail           = try(each.value.log_fail, null)
  log_success        = try(each.value.log_success, null)

}
